all: fw421_reset fw421_block_port fw421_unblock_port fw421_query fc421_block_file fc421_unblock_file fc421_query fc421_reset

fw421_reset: fw421_reset.c
fw421_block_port: fw421_block_port.c
fw421_unblock_port: fw421_unblock_port.c
fw421_query: fw421_query.c
fc421_reset: fc421_reset.c
fc421_block_file: fc421_block_file.c
fc421_unblock_file: fc421_unblock_file.c
fc421_query: fc421_query.c

